# Scrutinizer CI configuration file.
# @link https://scrutinizer-ci.com/

# For use with the Dyna WordPress theme
# @link https://github.com/dyna-press/dyna

# Declare project language and define checks
# @link https://scrutinizer-ci.com/docs/guides/php/automated-code-reviews
# @link https://scrutinizer-ci.com/docs/guides/javascript/

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
          - command: phpcs-run
            use_website_config: true   # <- uses the website config
#          - command: phpcs-run --config phpcs.xml
          - js-scrutinizer-run

# Do checks on PHP and Javascript
# @link https://scrutinizer-ci.com/g/dyna-press/dyna/settings/build-config

checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        psr2_control_structure_declaration: false
        avoid_superglobals: true
        security_vulnerabilities: true
        no_exit: true
        simplify_boolean_return: true
        return_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        param_doc_comment_if_not_inferrable: true
        overriding_parameter: true
        no_short_variable_names:
            minimum: '3'
        no_short_method_names:
            minimum: '3'
        no_long_variable_names:
            maximum: '20'
        no_goto: true
        naming_conventions:
            local_variable: '^[a-z][a-zA-Z0-9]*$'
            abstract_class_name: ^Abstract|Factory$
            utility_class_name: 'Utils?$'
            constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
            property_name: '^[a-z][a-zA-Z0-9]*$'
            method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
            parameter_name: '^[a-z][a-zA-Z0-9]*$'
            interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
            type_name: '^[A-Z][a-zA-Z0-9]*$'
            exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
            isser_method_name: '^(?:is|has|should|may|supports)'
        more_specific_types_in_doc_comments: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        fix_line_ending: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
    javascript:
        no_var: true
        no_param_assign: true
        no_loop_var_assign: true
        no_implicit_undefined_return: true
        no_else_return: true
        no_alert: true
        eqeqeq: true

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            around_operators:
                concatenation: true
                negation: true

# Declare project language and PHP versions to test against.
# @link https://scrutinizer-ci.com/docs/guides/php/continuous-integration-deployment

build:
    environment:
        php:
            version: 7.2       # Common versions: 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, or hhvm

# Analyze code coverage
# @link https://scrutinizer-ci.com/docs/build/code_coverage
# @link https://scrutinizer-ci.com/docs/tools/external-code-coverage/

build:
    tests:
        override:
        - command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
          coverage:
                file: 'coverage.xml'
                format: 'clover'

build:
    nodes:
        coverage:
            tests:
                override:
                - command: vendor/bin/phpunit --coverage-clover=clover.xml
                  coverage:
                      file: coverage.xml
                      format: clover

# Set dependency for WordPress
# @link https://scrutinizer-ci.com/docs/tools/php/php-scrutinizer/analyzing-wordpress

build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress


# Use filter
# @link https://scrutinizer-ci.com/docs/reviews/excluding_files_from_analysis

filter:
    excluded_paths:
        - languages/*
        - gulpfile.js
        - docs/
    dependency_paths:
        - vendor/